package ru.binarysimple.delivery.model;

public enum EventType {
    ORDER_CREATED,
    ORDER_CANCELLING,
    ORDER_CANCELED,


//    PAYMENT_COMPLETED,
//    PAYMENT_REQUESTED,
//    PAYMENT_REFUNDED,
//    PAYMENT_FAILED,
//    PAYMENT_COMPENSATION_COMPLETED,
//    PAYMENT_COMPENSATION_FAILED,


    DELIVERY_RESERVED,
    DELIVERY_REQUESTED,
    DELIVERY_CANCELED,
    DELIVERY_RESERVATION_FAILED,
    DELIVERY_COMPENSATION_COMPLETED,
    DELIVERY_COMPENSATION_FAILED
//
//
//    DELIVERY_SCHEDULED,
//    DELIVERY_REQUESTED,
//    DELIVERY_CANCELLED,
//    DELIVERY_FAILED,
//    NOTIFICATION_SENT,
//    SAGA_COMPLETED,
//    SAGA_COMPENSATED
}
